version: "3.3"

services:

  palis_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: palis_web
    container_name: palis_web
    volumes:
      - .:/code
    command: ./docker_commands.sh
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8000:8000
